spring:
  datasource:
    password: India@123
    url: jdbc:mysql://localhost:3306/je8?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 9090
